"use client";

import { useMemo, useState } from "react";
import styles from "./field.module.css";

const terminal=new Set(["completed","failed","cancelled","validation_pending"]);
const readable=(value)=>String(value||"").replaceAll("_"," ");
const time=(value)=>value?new Date(`${String(value).replace(" ","T")}Z`).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):"";
const todayLabel=(value)=>new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date(`${value}T12:00:00`));

function geo(){return new Promise((resolve)=>{if(!navigator.geolocation)return resolve({});navigator.geolocation.getCurrentPosition((position)=>resolve({latitude:position.coords.latitude,longitude:position.coords.longitude}),()=>resolve({}),{enableHighAccuracy:false,timeout:4500,maximumAge:60000})})}
async function compressedPhoto(file){if(!file||!/^image\/(jpeg|png|webp)$/.test(file.type))return file;try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise((resolve)=>canvas.toBlob(resolve,"image/jpeg",.76));return blob||file}catch{return file}}

export default function FieldClient({initialDay}){
  const [day,setDay]=useState(initialDay);const [loading,setLoading]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [routeOpen,setRouteOpen]=useState(false);const [exceptionTask,setExceptionTask]=useState(null);const [finishOpen,setFinishOpen]=useState(false);const [proofLoading,setProofLoading]=useState("");
  const route=day.route;const shift=day.shift;const locations=route?.locations||[];const current=useMemo(()=>locations.find((location)=>location.status!=="completed")||locations.at(-1)||null,[locations]);const remaining=route?route.totals.tasks-route.totals.completed:0;const progress=route?.totals.tasks?Math.round(route.totals.completed/route.totals.tasks*100):0;
  async function parse(response){if(response.status===401){window.location.assign("/field/login/");throw new Error("Your session expired.")}const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"The action could not be completed.");return data}
  async function refresh(){const data=await parse(await fetch(`/api/field/today/?date=${day.date}`,{cache:"no-store"}));setDay(data.day)}
  async function action(body){if(loading)return;setLoading(body.action);setError("");setNotice("");try{const position=await geo();const data=await parse(await fetch("/api/field/action/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,...position,shiftId:shift.id,date:day.date})}));if(data.day)setDay(data.day);else await refresh();setNotice(data.message||"Saved.");return true}catch(requestError){setError(requestError.message);return false}finally{setLoading("")}}
  async function signOut(){setLoading("signout");try{await fetch("/api/field/session/",{method:"DELETE"})}finally{window.location.assign("/field/login/")}}
  async function uploadProof(task,file){if(!file)return;setProofLoading(task.id);setError("");try{const photo=await compressedPhoto(file);if(photo.size>1250*1024)throw new Error("This photo is still too large after compression. Retake it with the standard camera setting.");const position=await geo();const params=new URLSearchParams({taskId:task.id,...Object.fromEntries(Object.entries(position).map(([key,value])=>[key,String(value)]))});const data=await parse(await fetch(`/api/field/photo/?${params}`,{method:"PUT",headers:{"Content-Type":photo.type||file.type},body:photo}));await refresh();setNotice("Delivery photo added.");return data}catch(requestError){setError(requestError.message)}finally{setProofLoading("")}}

  return <><header className={styles.header}><a className={styles.brand} href="/field/"><span>O</span><div><strong>OPWP</strong><small>Field</small></div></a><div className={styles.headerCenter}><span>{todayLabel(day.date)}</span><strong>{route?`${route.locationCount} stops · ${remaining} tasks left`:"No route released"}</strong></div><button className={styles.avatar} type="button" onClick={signOut} title="Sign out" aria-label={`Sign out ${day.member?.name||"technician"}`}>{String(day.member?.name||"T").slice(0,1).toUpperCase()}</button></header>
    <div className={styles.progressBar}><span style={{width:`${progress}%`}}/></div>
    <section className={styles.content}>
      <div className={styles.greeting}><span>{shift?.status==="completed"?"Route complete":shift?.status==="in_progress"?"Route in progress":"Today’s route"}</span><h1>{shift?.status==="in_progress"?`Keep moving, ${String(day.member?.name||"").split(" ")[0]}.`:`Good ${new Date().getHours()<12?"morning":"afternoon"}, ${String(day.member?.name||"").split(" ")[0]}.`}</h1></div>
      <div className={styles.messages} aria-live="polite">{error?<div className={styles.error} role="alert">{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}</div>
      {!route?<NoRoute date={day.date}/>:shift.status==="pending_load"?<LoadCheck route={route} loading={loading} onConfirm={action}/>:shift.status==="ready"?<Ready route={route} loading={loading} onStart={action}/>:shift.status==="completed"?<Completed day={day}/>:<ActiveRoute route={route} shift={shift} current={current} loading={loading} proofLoading={proofLoading} onAction={action} onProof={uploadProof} onException={setExceptionTask} onRoute={()=>setRouteOpen(true)} onFinish={()=>setFinishOpen(true)}/>}
    </section>
    {shift?.status==="in_progress"?<nav className={styles.bottomNav}><button onClick={()=>setRouteOpen(true)}><span>☷</span>Route</button><button className={styles.nextButton} onClick={()=>current&&document.getElementById("current-stop")?.scrollIntoView({behavior:"smooth"})}><span>{current?.sequence||"✓"}</span>Current stop</button><button onClick={()=>action({action:shift.activeBreak?"end_break":"start_break",breakType:"paid_break"})}><span>{shift.activeBreak?"▶":"Ⅱ"}</span>{shift.activeBreak?"Resume":"Break"}</button></nav>:null}
    {routeOpen?<RouteDrawer route={route} onClose={()=>setRouteOpen(false)}/>:null}
    {exceptionTask?<ExceptionModal task={exceptionTask} loading={loading} onClose={()=>setExceptionTask(null)} onSubmit={async(body)=>{if(await action({action:"fail_task",taskId:exceptionTask.id,...body}))setExceptionTask(null)}}/>:null}
    {finishOpen?<FinishModal route={route} shift={shift} loading={loading} onClose={()=>setFinishOpen(false)} onSubmit={async(body)=>{if(await action({action:"complete_route",...body}))setFinishOpen(false)}}/>:null}
  </>;
}

function NoRoute({date}){return <section className={styles.stateCard}><div className={styles.stateIcon}>✓</div><span>No route released</span><h2>You’re clear for now.</h2><p>Management has not released a route to your field account for {todayLabel(date)}. Pull down or refresh after dispatch is finalized.</p><button onClick={()=>window.location.reload()}>Check again</button></section>}

function LoadCheck({route,loading,onConfirm}){const [counts,setCounts]=useState(Object.fromEntries(route.load.items.map((item)=>[item.product_id,Number(item.required_quantity)||0])));const [mileage,setMileage]=useState("");return <section className={styles.loadCard}><div className={styles.stepBadge}>Departure check · 1 of 2</div><h2>Confirm what’s in the vehicle.</h2><p>Payment is validated. Count the scheduled bags and any approved buffer before leaving.</p><div className={styles.validation}><span>✓</span><div><strong>Payments cleared</strong><small>{route.foodTaskCount?`${route.foodTaskCount} food deliveries are ready.`:"No food deliveries on this route."}</small></div></div>{route.load.items.length?<div className={styles.loadList}>{route.load.items.map((item)=><label key={item.product_id}><div><strong>{item.formula_code} · {item.color} bag</strong><small>{item.bag_weight_lb} lb · {item.required_quantity} required</small></div><div><button type="button" onClick={()=>setCounts({...counts,[item.product_id]:Math.max(0,counts[item.product_id]-1)})}>−</button><input aria-label={`${item.formula_code} loaded`} inputMode="numeric" value={counts[item.product_id]} onChange={(event)=>setCounts({...counts,[item.product_id]:Number(event.target.value)||0})}/><button type="button" onClick={()=>setCounts({...counts,[item.product_id]:counts[item.product_id]+1})}>+</button></div></label>)}</div>:<div className={styles.noFood}>No dog-food load is required today.</div>}<label className={styles.mileage}>Starting mileage <input inputMode="decimal" value={mileage} onChange={(event)=>setMileage(event.target.value)} placeholder="Optional for personal vehicles"/></label><button className={styles.fullButton} disabled={Boolean(loading)} onClick={()=>onConfirm({action:"confirm_load",startingMileage:mileage,items:route.load.items.map((item)=>({productId:item.product_id,quantity:counts[item.product_id]}))})}>{loading?"Confirming…":"Confirm load & continue"}</button></section>}

function Ready({route,loading,onStart}){return <section className={styles.stateCard}><div className={styles.stateIcon}>✓</div><span>Departure check complete</span><h2>{route.locationCount} stops are ready.</h2><p>Your route includes {route.sourceJobCount} scooping jobs and {route.foodTaskCount} dog-food deliveries. Start only when you are ready to leave.</p><div className={styles.readyStats}><div><b>{route.locationCount}</b><small>Stops</small></div><div><b>{route.sourceJobCount}</b><small>Scoops</small></div><div><b>{route.foodTaskCount}</b><small>Food</small></div></div><button className={styles.fullButton} disabled={Boolean(loading)} onClick={()=>onStart({action:"start_route"})}>{loading?"Starting…":"Start today’s route →"}</button></section>}

function ActiveRoute({route,shift,current,loading,proofLoading,onAction,onProof,onException,onRoute,onFinish}){const allDone=route.totals.completed===route.totals.tasks;return <>{shift.activeBreak?<div className={styles.breakBanner}><span>Ⅱ</span><div><strong>{readable(shift.activeBreak.break_type)} in progress</strong><small>Started {time(shift.activeBreak.started_at)}</small></div><button type="button" onClick={()=>onAction({action:"end_break"})}>Resume route</button></div>:null}{allDone?<section className={styles.stateCard}><div className={styles.stateIcon}>✓</div><span>Every task accounted for</span><h2>Close out the route.</h2><p>Confirm ending mileage and the remaining food load before clocking the route complete.</p><button type="button" className={styles.fullButton} onClick={onFinish}>Finish route</button></section>:current?<section className={styles.stopCard} id="current-stop"><div className={styles.stopTop}><div className={styles.stopNumber}><small>Stop</small><strong>{current.sequence}</strong><span>of {route.locationCount}</span></div><button type="button" onClick={onRoute}>View full route</button></div><div className={styles.customer}><span>{current.status==="arrived"?"At location":"Next location"}</span><h2>{current.customerName}</h2><p>{current.address}</p><div><a href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(current.address)}`} target="_blank" rel="noreferrer">Navigate ↗</a><small>About {Math.round(current.estimatedMinutes)} min on site</small></div></div>{current.tasks.some((task)=>task.type==="dog_food"&&!terminal.has(task.status))?<OnTheWay tasks={current.tasks} estimatedDriveMinutes={current.estimatedDriveMinutes} onAction={onAction} loading={loading}/>:null}{current.status!=="arrived"?<button type="button" className={styles.arriveButton} disabled={Boolean(loading)} onClick={()=>onAction({action:"arrive",locationId:current.id})}>I’ve arrived</button>:<div className={styles.taskList}>{current.tasks.map((task)=><TaskCard key={task.id} task={task} loading={loading} proofLoading={proofLoading} onAction={onAction} onProof={onProof} onException={onException}/>)}</div>}</section>:null}</>}

function OnTheWay({tasks,estimatedDriveMinutes,onAction,loading}){const task=tasks.find((item)=>item.type==="dog_food"&&!terminal.has(item.status));const options=[10,15,25,30,45,60];const estimate=Number(estimatedDriveMinutes)||15;const recommended=options.reduce((best,value)=>Math.abs(value-estimate)<Math.abs(best-estimate)?value:best,options[0]);const [selection,setSelection]=useState({taskId:task.id,lead:recommended});const lead=selection.taskId===task.id?selection.lead:recommended;if(task.noticeQueued)return <div className={`${styles.onWay} ${styles.onWayComplete}`}><div><span>Extreme Dog Fuel</span><strong>On-the-way notice queued</strong><small>The customer notification is recorded for this delivery.</small></div><b aria-label="Notice queued">✓</b></div>;return <div className={styles.onWay}><div><span>Extreme Dog Fuel</span><strong>Let them know you’re on the way.</strong><small>Planned-route recommendation: {recommended} minutes</small></div><select aria-label="Customer notice lead time" value={lead} onChange={(event)=>setSelection({taskId:task.id,lead:Number(event.target.value)})}>{options.map((value)=><option key={value} value={value}>{value} min</option>)}</select><button type="button" disabled={Boolean(loading)} onClick={()=>onAction({action:"on_the_way",taskId:task.id,leadMinutes:lead,recommendedLeadMinutes:recommended})}>Queue notice</button></div>}

function TaskCard({task,loading,proofLoading,onAction,onProof,onException}){const [placement,setPlacement]=useState(false);const done=terminal.has(task.status);const deliveryReady=task.type!=="dog_food"||(task.proofCount>0&&placement);return <article className={`${styles.taskCard} ${task.type==="dog_food"?styles.foodTask:""} ${done?styles.doneTask:""}`}><header><span>{task.type==="dog_food"?"Food delivery":"Scooping"}</span><small>{readable(task.status)}</small></header><h3>{task.type==="dog_food"?task.productSummary||"Extreme Dog Fuel":task.customerName||"Scooping service"}</h3>{task.type==="dog_food"?<><p className={styles.placement}>{task.placementNote||"Confirm the delivery placement with the customer instructions."}</p>{!done?<label className={styles.photoButton}>{proofLoading===task.id?"Uploading photo…":task.proofCount?"✓ Delivery photo added":"Take delivery photo"}<input type="file" accept="image/jpeg,image/png,image/webp,image/heic" capture="environment" disabled={Boolean(proofLoading)} onChange={(event)=>{const file=event.target.files?.[0];event.target.value="";onProof(task,file)}}/></label>:null}{!done?<label className={styles.check}><input type="checkbox" checked={placement} onChange={(event)=>setPlacement(event.target.checked)}/><span>Bag placed as requested</span></label>:null}{task.status==="in_progress"&&!deliveryReady?<p className={styles.requirementHint}>Add the delivery photo and confirm placement to finish this stop.</p>:null}</>:<>{!done?<a className={styles.sngButton} href="https://client.sweepandgo.com/login" target="_blank" rel="noreferrer">Open Sweep &amp; Go ↗</a>:null}{task.status==="validation_pending"?<p className={styles.validationPending}>✓ Recorded here · waiting for CRM validation</p>:null}</>} {!done?<div className={styles.taskActions}>{task.status==="in_progress"?<button type="button" disabled={Boolean(loading)||!deliveryReady} onClick={()=>onAction({action:"complete_task",taskId:task.id,placementConfirmed:placement})}>Complete {task.type==="dog_food"?"delivery":"task"}</button>:<button type="button" disabled={Boolean(loading)} onClick={()=>onAction({action:"start_task",taskId:task.id})}>Start task</button>}<button type="button" className={styles.issueButton} onClick={()=>onException(task)}>Report issue</button></div>:null}</article>}

function Completed({day}){return <section className={styles.stateCard}><div className={styles.stateIcon}>★</div><span>Route complete</span><h2>Nice work, {String(day.member?.name||"").split(" ")[0]}.</h2><p>{day.route.locationCount} stops are closed out. Management can now review mileage, inventory, exceptions, and CRM validation.</p><div className={styles.readyStats}><div><b>{day.route.totals.completed}</b><small>Tasks</small></div><div><b>{day.route.totals.stopsCompleted}</b><small>Stops</small></div><div><b>100%</b><small>Complete</small></div></div></section>}

function RouteDrawer({route,onClose}){return <div className={styles.drawerBackdrop} role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose()}}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="field-route-title"><header><div><span>Today’s route</span><h2 id="field-route-title">{route.locationCount} stops</h2></div><button type="button" onClick={onClose} aria-label="Close route overview">×</button></header><ol>{route.locations.map((location)=><li className={location.status==="completed"?styles.locationDone:""} key={location.id}><span>{location.status==="completed"?"✓":location.sequence}</span><div><strong>{location.customerName}</strong><p>{location.address}</p><small>{location.tasks.map((task)=>task.type==="dog_food"?"Food":"Scoop").join(" + ")}</small></div></li>)}</ol></aside></div>}

function ExceptionModal({task,loading,onClose,onSubmit}){const [reason,setReason]=useState("");const [disposition,setDisposition]=useState("return_to_vehicle");const [notes,setNotes]=useState("");return <div className={styles.modalBackdrop} role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="field-exception-title"><span>Field exception</span><h2 id="field-exception-title">What happened?</h2><p>Management will review this before any customer or inventory follow-up.</p><label>Reason<select autoFocus value={reason} onChange={(event)=>setReason(event.target.value)}><option value="">Select a reason</option><option>No access</option><option>Customer requested change</option><option>Unsafe conditions</option><option>Product damaged</option><option>Wrong product or quantity</option><option>Other</option></select></label>{task.type==="dog_food"?<label>Food disposition<select value={disposition} onChange={(event)=>setDisposition(event.target.value)}><option value="return_to_vehicle">Return to vehicle</option><option value="return_to_warehouse">Return to warehouse</option><option value="damaged">Damaged</option><option value="missing">Missing</option></select></label>:null}<label>Notes<textarea value={notes} onChange={(event)=>setNotes(event.target.value)} placeholder="Add anything management needs to know"/></label><div><button type="button" onClick={onClose}>Cancel</button><button type="button" disabled={!reason||Boolean(loading)} onClick={()=>onSubmit({reason,inventoryDisposition:disposition,notes})}>Submit issue</button></div></section></div>}

function FinishModal({route,shift,loading,onClose,onSubmit}){const [mileage,setMileage]=useState("");const [notes,setNotes]=useState("");const [items,setItems]=useState(Object.fromEntries(route.load.items.map((item)=>[item.product_id,Math.max(0,Number(item.loaded_quantity)-Number(item.delivered_quantity))])));const mileageInvalid=mileage!==""&&(!Number.isFinite(Number(mileage))||Number(mileage)<0||(shift.startingMileage!=null&&Number(mileage)<Number(shift.startingMileage)));return <div className={styles.modalBackdrop} role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="field-finish-title"><span>End-of-route check</span><h2 id="field-finish-title">Close out the day.</h2><p>Confirm what is coming back before the route is locked.</p>{route.load.items.map((item)=>{const maximum=Math.max(0,Number(item.loaded_quantity)-Number(item.delivered_quantity));return <label key={item.product_id}>{item.formula_code} returned <small>{maximum} available</small><input inputMode="numeric" min="0" max={maximum} value={items[item.product_id]} onChange={(event)=>setItems({...items,[item.product_id]:Math.min(maximum,Math.max(0,Number(event.target.value)||0))})}/></label>})}<label>Ending mileage {shift.startingMileage!=null?<small>Started at {shift.startingMileage}</small>:null}<input autoFocus inputMode="decimal" value={mileage} aria-invalid={mileageInvalid} onChange={(event)=>setMileage(event.target.value)}/></label>{mileageInvalid?<p className={styles.fieldError}>Ending mileage must be at least {shift.startingMileage??0}.</p>:null}<label>Route notes<textarea value={notes} onChange={(event)=>setNotes(event.target.value)} placeholder="Optional notes for management"/></label><div><button type="button" onClick={onClose}>Keep route open</button><button type="button" disabled={Boolean(loading)||mileageInvalid} onClick={()=>onSubmit({endingMileage:mileage,notes,items:route.load.items.map((item)=>({productId:item.product_id,returned:items[item.product_id]}))})}>Complete route</button></div></section></div>}
