import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { verifyAdminRequest } from "@/lib/admin-auth";
import { getQuickBooksFinancialDashboard } from "@/lib/quickbooks";
import styles from "./financials.module.css";

export const dynamic = "force-dynamic";
export const metadata = { title: "Financials | OPWP Executive Cockpit", robots: { index: false, follow: false } };

const money = (value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value) || 0);
const pct = (value) => `${Number(value || 0).toFixed(1)}%`;

function Trend({ rows = [] }) {
  const width = 760, height = 210;
  const max = Math.max(...rows.flatMap((row) => [row.revenue, row.expenses, Math.abs(row.netIncome)]), 1);
  const step = rows.length > 1 ? width / (rows.length - 1) : width;
  const points = (key) => rows.map((row, index) => `${index * step},${height - 24 - ((Number(row[key]) || 0) / max) * 165}`).join(" ");
  return <><svg className={styles.chart} viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Monthly income statement trend">{[45,95,145,185].map((y)=><line key={y} x1="0" y1={y} x2={width} y2={y} stroke="#edf0ec"/>)}<polyline points={points("revenue")} fill="none" stroke="#315f7d" strokeWidth="3" strokeLinecap="round"/><polyline points={points("expenses")} fill="none" stroke="#b67850" strokeWidth="3" strokeLinecap="round"/><polyline points={points("netIncome")} fill="none" stroke="#57864a" strokeWidth="4" strokeLinecap="round"/>{rows.map((row,index)=><text key={row.label} x={index*step} y={height-4} textAnchor={index===0?"start":index===rows.length-1?"end":"middle"} fontSize="9" fill="#8b979b">{row.label}</text>)}</svg></>;
}

function Aging({ map }) {
  const entries = [...(map?.entries?.() ?? [])].filter(([label, value]) => value > 0 && /current|1.?30|31.?60|61.?90|over.?90|total/i.test(label));
  const max = Math.max(...entries.map(([,value])=>value),1);
  return <div className={styles.barGroup}>{entries.length ? entries.map(([label,value])=><div key={label}><div className={styles.barLabel}><span>{label}</span><span>{money(value)}</span></div><div className={styles.barTrack}><div className={styles.barFill} style={{width:`${Math.max((value/max)*100,2)}%`}}/></div></div>) : <div className={styles.muted}>No aging balances returned.</div>}</div>;
}

export default async function FinancialsPage() {
  const auth = await verifyAdminRequest(await headers());
  if (!auth.authorized) redirect("/");
  const data = await getQuickBooksFinancialDashboard();
  if (!data.connected) redirect("/admin/");
  const currentLiabilityAccounts = (data.accounts ?? []).filter((account)=>/current liability|accounts payable|credit card/i.test(`${account.type} ${account.subtype}`));
  const derivedCurrentAssets = data.currentAssets || (data.cash || 0) + (data.accountsReceivable || 0);
  const derivedCurrentLiabilities = data.currentLiabilities || currentLiabilityAccounts.reduce((sum, account) => sum + Math.abs(account.balance || 0), 0);
  const workingCapital = derivedCurrentAssets - derivedCurrentLiabilities;
  const avgExpenses = data.monthly?.length ? data.monthly.reduce((sum,row)=>sum+row.expenses,0)/data.monthly.length : 0;
  const runway = avgExpenses > 0 ? data.cash / avgExpenses : 0;
  const segments = [...(data.classes ?? []), ...(data.locations ?? [])];
  const banks = (data.accounts ?? []).filter((account)=>/bank|cash/i.test(account.type));
  const liabilities = (data.accounts ?? []).filter((account)=>/liability|credit card/i.test(account.type));
  const cogsTracked = Number(data.costOfGoodsSold) > 0;
  return <main className={`${styles.shell} opwp-admin-shell`}><div className={styles.wrap}>
    <header className={styles.header}><div><div className={styles.eyebrow}>QuickBooks Online · {data.environment}</div><h1 className={styles.title}>Financial command center</h1><div className={styles.muted}>{data.companyName} · Accrual basis · through {data.periodEnd}</div></div><div className={styles.muted}>Signed in as {auth.email}</div></header>
    <nav className={styles.nav}><a href="/admin/">Overview</a><a href="/admin/financials/">Financials</a><a href="#performance">Performance</a><a href="#position">Position</a><a href="#decisions">Decisions</a></nav>
    {!data.ok ? <div className={styles.warning}>{data.error} Return to the <a href="/admin/">overview</a> for connection status.</div> : <>
    {data.warnings?.length ? <div className={styles.muted} style={{marginBottom:14}}>Data availability: {data.warnings.join(" ")} Core statements are unaffected.</div> : null}
    <section className={styles.hero}><div className={styles.heroMain}><div className={styles.label}>Cash available</div><div className={styles.heroValue}>{money(data.cash)}</div><div className={styles.heroSub}>{runway > 0 ? `${runway.toFixed(1)} months of trailing average expenses` : "Runway appears after monthly expense history is available"}</div><div className={styles.healthLine}><span className={styles.dot}/>QuickBooks feed healthy · connection persists automatically</div></div><div className={styles.heroAside}><div className={styles.heroMetric}><div className={styles.label}>MTD revenue</div><div className={styles.heroValue}>{money(data.revenue)}</div></div><div className={styles.heroMetric}><div className={styles.label}>Net income</div><div className={styles.heroValue}>{money(data.netIncome)}</div></div><div className={styles.heroMetric}><div className={styles.label}>Gross margin</div><div className={styles.heroValue}>{cogsTracked ? pct(data.grossMargin) : "Not tracked"}</div><div className={styles.heroSub}>{cogsTracked ? money(data.costOfGoodsSold) + " direct cost" : "COGS is not classified in QuickBooks"}</div></div><div className={styles.heroMetric}><div className={styles.label}>Working capital</div><div className={styles.heroValue}>{money(workingCapital)}</div></div></div></section>
    <section id="performance" className={styles.section}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>Performance</div><h2 className={styles.sectionTitle}>How the year is moving</h2><div className={styles.muted}>The current month is partial through {data.periodEnd}.</div></div><div className={styles.legend}><span className={styles.key} style={{"--color":"#315f7d"}}>Revenue</span><span className={styles.key} style={{"--color":"#b67850"}}>Expenses</span><span className={styles.key} style={{"--color":"#57864a"}}>Net income</span></div></div><div className={styles.grid2}><div className={styles.panel}><Trend rows={data.monthly}/></div><div className={styles.panel}><div className={styles.eyebrow}>Margin bridge · MTD</div><div className={styles.statement}><div className={styles.statementRow}><strong>Revenue</strong><span>{money(data.revenue)}</span></div><div className={styles.statementRow}><strong>Direct costs</strong><span>{cogsTracked ? `(${money(data.costOfGoodsSold)})` : "Not classified"}</span></div><div className={styles.statementRow}><strong>Gross profit</strong><span>{money(data.grossProfit)}</span></div><div className={styles.statementRow}><strong>Operating expenses</strong><span>({money(data.expenses)})</span></div><div className={`${styles.statementRow} ${styles.total} ${data.netIncome<0?styles.negative:""}`}><strong>Net income</strong><span>{money(data.netIncome)} · {pct(data.netMargin)}</span></div></div></div></div></section>
    <section id="position" className={styles.section}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>Financial position</div><h2 className={styles.sectionTitle}>Liquidity, obligations, and capital</h2></div></div><div className={styles.equal}><div className={styles.panel}><div className={styles.balance}><div className={styles.balanceGroup}><h3>Assets</h3><div className={styles.balanceItem}><span>Cash</span><b>{money(data.cash)}</b></div><div className={styles.balanceItem}><span>Accounts receivable</span><b>{money(data.accountsReceivable)}</b></div><div className={styles.balanceItem}><span>Current assets</span><b>{money(derivedCurrentAssets)}</b></div></div><div className={styles.balanceGroup}><h3>Obligations & equity</h3><div className={styles.balanceItem}><span>Current liabilities</span><b>{money(derivedCurrentLiabilities)}</b></div><div className={styles.balanceItem}><span>Total liabilities</span><b>{money(data.totalLiabilities)}</b></div><div className={styles.balanceItem}><span>Total equity</span><b>{money(data.totalEquity)}</b></div></div></div></div><div className={styles.panel}><div className={styles.eyebrow}>Receivables aging</div><div style={{marginTop:14}}><Aging map={data.receivablesAging}/></div></div></div></section>
    <section id="decisions" className={styles.section}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>Owner decisions</div><h2 className={styles.sectionTitle}>What the books can support</h2></div></div><div className={styles.equal}><div className={styles.panel}><div className={styles.decision}><h3>Capital readiness</h3><p>Available working capital is {money(workingCapital)}. Truck affordability will be modeled against a protected cash reserve, monthly debt service, and route capacity—not merely the bank balance.</p></div><div className={styles.decision} style={{marginTop:11}}><h3>Growth investment</h3><p>Advertising capacity will be tied to contribution margin, customer acquisition payback, churn, and cash runway. Target assumptions will remain explicit and editable.</p></div></div><div className={styles.panel}><div className={styles.eyebrow}>Business-line structure</div>{segments.length?<><p className={styles.muted} style={{marginTop:9}}>QuickBooks segmentation found. These dimensions will drive OPWP versus Extreme Dog Fuel reporting.</p><div className={styles.tags}>{segments.map((item)=><span className={styles.tag} key={`${item.id}-${item.name}`}>{item.name}</span>)}</div></>:<div className={styles.warning} style={{marginTop:12}}>No active QuickBooks classes or locations were found. OPWP and Extreme Dog Fuel cannot yet be separated reliably from the general ledger. We can use product/service and account mappings, or create classes in QuickBooks.</div>}</div></div></section>
    <section className={styles.section}><div className={styles.equal}><div className={styles.panel}><div className={styles.eyebrow}>Cash accounts</div><table className={styles.table}><tbody>{banks.map((account)=><tr key={account.id}><td>{account.name}</td><td>{account.type}</td><td>{money(account.balance)}</td></tr>)}</tbody></table></div><div className={styles.panel}><div className={styles.eyebrow}>Liability accounts</div><table className={styles.table}><tbody>{liabilities.map((account)=><tr key={account.id}><td>{account.name}</td><td>{account.type}</td><td>{money(account.balance)}</td></tr>)}</tbody></table></div></div></section>
    </>}</div></main>;
}
